name: deploy-pages
on:
  push:
    branches: "main"
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/deploy-pages.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - id: configure-pages
        uses: actions/configure-pages@v4
      - run: npm run build
        env:
          BASE_URL: ${{ steps.configure-pages.outputs.base_url }}/
          BASE_PATH: ${{ steps.configure-pages.outputs.base_path }}/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist
      - id: deploy-pages
        uses: actions/deploy-pages@v4